version: '3'

tasks:
  css:
    desc: Build css
    cmds:
      - tailwindcss -i ./web/assets/tw.css -o ./web/assets/styles.css

  build:
    desc: Generate templates and index.html
    cmds:
      - GOARCH=wasm GOOS=js go build -o web/app.wasm src/*.go
      - go build -o run src/*.go

  run:
    desc: Run application
    deps:
      - css
      - build
    cmds:
      - ./run
